
[font]
size = 12

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "BoldItalic"

[font.italic]
family = "MesloLGS NF"
style = "MediumItalic"

[font.normal]
family = "MesloLGS NF"
style = "Medium"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.8

[window.class]
general = "Alacritty"
instance = "Alacritty"

[colors]
draw_bold_text_with_bright_colors = true
